version: '3'

services:
  mongodb:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - ecommerce_network

  shopfront:
    build: ./ShopFront
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
    depends_on:
      - mongodb
    networks:
      - ecommerce_network

  product-catalogue:
    build: ./ProductCatalogue
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
    depends_on:
      - mongodb
    networks:
      - ecommerce_network

  stock-manager:
    build: ./StockManager
    ports:
      - "5002:5002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
    depends_on:
      - mongodb
    networks:
      - ecommerce_network

  user-profile:
    build: ./UserProfile
    ports:
      - "5003:5003"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ecommerce
    depends_on:
      - mongodb
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge

volumes:
  mongodb_data: